# Generated by Django 5.1.1 on 2024-09-29 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zonelivraison',
            name='numero',
            field=models.PositiveIntegerField(default=2, unique=True),
            preserve_default=False,
        ),
    ]
