# Generated by Django 5.0 on 2024-09-25 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='QuantiteStock',
            field=models.IntegerField(default=1),
        ),
    ]
