# Generated by Django 5.0 on 2024-09-25 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_produit_quantitestock'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='couleur',
            field=models.CharField(blank=True, choices=[('BL', 'Bleu'), ('RD', 'Rouge'), ('GR', 'Vert'), ('YW', 'Jaune'), ('BK', 'Noir'), ('WH', 'Blanc'), ('OR', 'Orange'), ('PR', 'Pourpre'), ('PK', 'Rose'), ('GY', 'Gris'), ('BR', 'Marron')], max_length=128, null=True),
        ),
    ]
