# Generated by Django 5.1.1 on 2024-09-13 22:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0002_temoignage"),
    ]

    operations = [
        migrations.AddField(
            model_name="produit",
            name="nouveaute",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="temoignage",
            name="likes",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
