# Generated by Django 5.1.1 on 2024-09-13 22:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0003_produit_nouveaute_temoignage_likes"),
    ]

    operations = [
        migrations.RenameField(
            model_name="produit",
            old_name="nouveaute",
            new_name="special",
        ),
    ]
