# Generated by Django 5.0 on 2024-09-25 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_produit_couleur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
