# Generated by Django 5.1.1 on 2024-09-29 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_zonelivraison_numero'),
        ('shop', '0004_alter_produit_slug'),
    ]

    operations = [
    ]
