# Generated by Django 5.1.1 on 2024-09-29 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_merge_20240929_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='image',
            field=models.ImageField(default='', upload_to='images_categories/'),
            preserve_default=False,
        ),
    ]
