# Generated by Django 5.0 on 2024-09-29 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_categorie_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Temoignage',
        ),
    ]
