# Generated by Django 5.1.1 on 2024-10-03 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_delete_temoignage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='QuantiteStock',
            field=models.PositiveBigIntegerField(default=1),
        ),
    ]
