# Generated by Django 5.1.1 on 2024-10-05 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_produit_quantitestock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='achat_direct',
        ),
        migrations.AlterField(
            model_name='commande',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente de paiement'), ('PAYEE', 'Payée'), ('EN_PREPARATION', 'En préparation'), ('EN_COURS_LIVRAISON', 'En cours de Livraison'), ('LIVREE', 'Livrée'), ('ANNULEE', 'Annulée')], default='EN_ATTENTE', max_length=30),
        ),
    ]
