# Generated by Django 5.1.1 on 2024-10-08 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_remove_commande_achat_direct_alter_commande_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement',
            name='methode_paiement',
            field=models.CharField(choices=[('ORANGE_MONEY', 'Orange Money'), ('WAVE', 'Wave'), ('CC', 'Carte de crédit')], max_length=20),
        ),
    ]
