# Generated by Django 5.0 on 2024-10-06 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_produit_quantitestock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='description',
        ),
        migrations.AlterField(
            model_name='produit',
            name='QuantiteStock',
            field=models.PositiveBigIntegerField(default=1),
        ),
    ]
