# Generated by Django 5.1.1 on 2024-10-08 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_paiement_methode_paiement'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='id_transaction',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
