# Generated by Django 5.0 on 2024-10-06 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_remove_produit_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='QuantiteStock',
            field=models.PositiveBigIntegerField(blank=True, default=1),
        ),
    ]
