# Generated by Django 5.1.1 on 2024-10-09 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_paiement_id_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='panierproduit',
            name='quantite',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
