# Generated by Django 5.0 on 2024-10-06 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_alter_produit_quantitestock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='QuantiteStock',
            field=models.PositiveBigIntegerField(blank=True, default=1, null=True),
        ),
    ]
