# Generated by Django 5.0 on 2024-10-08 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_alter_produit_quantitestock'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='isDeletable',
            field=models.BooleanField(default=False),
        ),
    ]
