# Generated by Django 4.2 on 2024-10-14 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_produit_isdeletable'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='pointure',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
