# Generated by Django 5.1.1 on 2024-11-08 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_panierproduit_quantite'),
        ('shop', '0016_produit_pointure'),
    ]

    operations = [
    ]
