# Generated by Django 5.1.1 on 2025-01-14 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_merge_20241108_2242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='reserve',
        ),
        migrations.AddField(
            model_name='produit',
            name='description',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='neuf',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='commande',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente de paiement'), ('PAYEE', 'Payée'), ('EN_COURS_LIVRAISON', 'En cours de Livraison'), ('LIVREE', 'Livrée')], default='EN_ATTENTE', max_length=30),
        ),
        migrations.DeleteModel(
            name='Paiement',
        ),
    ]
