# Generated by Django 5.1.1 on 2024-12-26 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_merge_20241108_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente de paiement'), ('PAYEE', 'Payée'), ('EN_COURS_LIVRAISON', 'En cours de Livraison'), ('LIVREE', 'Livrée')], default='EN_ATTENTE', max_length=30),
        ),
    ]
