# Generated by Django 5.1.1 on 2025-01-10 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_produit_neuf_alter_commande_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='description',
            field=models.CharField(blank=True, null=True),
        ),
    ]
