# Generated by Django 5.1.1 on 2024-12-26 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_alter_commande_statut'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_commande', models.CharField(max_length=50, unique=True)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('methode_paiement', models.CharField(choices=[('ORANGE_MONEY', 'Orange Money'), ('WAVE', 'Wave'), ('CC', 'Carte de crédit')], max_length=20)),
                ('date_paiement', models.DateTimeField(auto_now_add=True)),
                ('id_transaction', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Paiement',
        ),
    ]
