# Generated by Django 5.1.1 on 2025-01-20 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_remove_produit_reserve_produit_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='nom',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
