# Generated by Django 5.1.1 on 2025-01-23 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_alter_produit_nom'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='date_expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
