# Generated by Django 5.1.1 on 2024-12-31 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_payment_delete_paiement'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='statut',
            field=models.CharField(default='pending', max_length=50),
        ),
    ]
