# Generated by Django 5.1.1 on 2025-01-08 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_payment_statut'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
