# Generated by Django 4.2.18 on 2025-01-28 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_alter_produit_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='panier',
            name='verrouille',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='commande',
            name='ref_code',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
    ]
