# Generated by Django 4.2.18 on 2025-01-29 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0022_panier_verrouille_alter_commande_ref_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produit",
            name="composition",
            field=models.CharField(
                blank=True,
                choices=[("coton", "Coton"), ("nilon", "Nilon"), ("jean", "Jean")],
                max_length=128,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="produit",
            name="taille",
            field=models.CharField(
                blank=True,
                choices=[
                    ("S", "S"),
                    ("M", "M"),
                    ("L", "L"),
                    ("XL", "XL"),
                    ("XXL", "XXL"),
                    ("48L", "48L"),
                    ("48M", "48M"),
                ],
                max_length=128,
                null=True,
            ),
        ),
    ]
