# Generated by Django 5.1.1 on 2025-02-06 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0023_alter_produit_composition_alter_produit_taille"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produit",
            name="composition",
            field=models.CharField(
                blank=True,
                choices=[
                    ("coton", "Coton"),
                    ("nilon", "Nilon"),
                    ("jean", "Jean"),
                    ("lin", "Lin"),
                ],
                max_length=128,
                null=True,
            ),
        ),
    ]
