# Generated by Django 5.1.1 on 2025-01-13 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_alter_produit_categorie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='reserve',
        ),
    ]
