# Generated by Django 5.1.1 on 2025-02-07 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0024_alter_produit_composition"),
    ]

    operations = [
        migrations.AddField(
            model_name="produit",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
