# Generated by Django 5.1.1 on 2025-02-07 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0025_produit_updated_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="produit",
            old_name="updated_at",
            new_name="Prod_updated_at",
        ),
    ]
