# Generated by Django 5.1.1 on 2025-02-07 22:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0026_rename_updated_at_produit_prod_updated_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="produit",
            old_name="Prod_updated_at",
            new_name="updated_at",
        ),
        migrations.AddField(
            model_name="produit",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
