# Generated by Django 5.0 on 2024-09-29 14:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_avis'),
    ]

    operations = [
        migrations.AddField(
            model_name='avis',
            name='temoigne_le',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
