# Generated by Django 5.1.1 on 2024-09-29 15:17

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_delete_codeotp'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='SN', unique=True)),
                ('otp_code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('nom_complet', models.CharField(max_length=255)),
                ('hashed_password', models.CharField(max_length=255)),
            ],
        ),
    ]
