# Generated by Django 5.1.1 on 2024-10-03 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_avis_temoigne_le'),
        ('accounts', '0004_codeotp'),
    ]

    operations = [
    ]
