# Generated by Django 5.1.1 on 2024-10-13 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_merge_0003_avis_temoigne_le_0004_codeotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='avis',
            name='nbre_etoiles',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='avis',
            name='Texte_avis',
            field=models.TextField(max_length=2000),
        ),
    ]
