# Generated by Django 4.2 on 2024-11-21 22:05

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_merge_0003_avis_temoigne_le_0004_codeotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='codeotp',
            name='addresse_mail',
            field=models.EmailField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='addresse_mail',
            field=models.EmailField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='codeotp',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='SN', unique=True),
        ),
    ]
