# Generated by Django 4.2 on 2024-11-21 22:09

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_codeotp_addresse_mail_customuser_addresse_mail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codeotp',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+221700000000', max_length=128, region='SN', unique=True),
            preserve_default=False,
        ),
    ]
