# Generated by Django 4.2 on 2024-11-21 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_codeotp_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codeotp',
            name='addresse_mail',
            field=models.EmailField(default='default@mail.sn', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='addresse_mail',
            field=models.EmailField(default='default@mail.sn', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
