# Generated by Django 5.1.1 on 2024-12-24 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_avis_nbre_etoiles_alter_avis_texte_avis'),
        ('accounts', '0009_codeotpresetpassword'),
    ]

    operations = [
    ]
