# Generated by Django 5.1.1 on 2025-01-19 16:23

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_merge_20241224_2138'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformationsGenerales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addresse_mail_site', models.EmailField(max_length=255)),
                ('telephone_site', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='SN')),
                ('adresse_site', models.CharField(max_length=255)),
                ('Lien_facebook', models.URLField()),
                ('Lien_instagram', models.URLField()),
                ('Lien_Whatsapp', models.URLField()),
            ],
            options={
                'verbose_name_plural': 'Informations generales',
            },
        ),
    ]
