# Generated by Django 5.1.1 on 2025-01-19 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_informationsgenerales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informationsgenerales',
            name='Lien_Whatsapp',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='informationsgenerales',
            name='Lien_facebook',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='informationsgenerales',
            name='Lien_instagram',
            field=models.URLField(null=True),
        ),
    ]
