# Generated by Django 5.1.1 on 2025-01-19 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_informationsgenerales_lien_whatsapp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informationsgenerales',
            name='Lien_Whatsapp',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='informationsgenerales',
            name='Lien_facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='informationsgenerales',
            name='Lien_instagram',
            field=models.URLField(blank=True, null=True),
        ),
    ]
