# Generated by Django 5.1.1 on 2025-01-19 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_informationsgenerales_lien_whatsapp_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='informationsgenerales',
            old_name='adresse_site',
            new_name='addresse_site',
        ),
    ]
