# Generated by Django 5.1.1 on 2025-01-23 17:58

import accounts.validators
import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_rename_adresse_site_informationsgenerales_addresse_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='SN', unique=True, validators=[accounts.validators.validate_phone_number_senegal]),
        ),
    ]
