# Generated by Django 5.1.1 on 2025-01-26 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_customuser_verification_token_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CodeOTP',
        ),
        migrations.DeleteModel(
            name='CodeOTPResetPassword',
        ),
        migrations.AddField(
            model_name='customuser',
            name='reset_password_token',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='reset_password_token_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
