# Generated by Django 5.1.1 on 2025-02-06 12:18

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0017_delete_codeotp_delete_codeotpresetpassword_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="addresse_mail",
            field=models.EmailField(
                max_length=255,
                unique=True,
                validators=[accounts.models.validate_email_domain],
            ),
        ),
    ]
