# Generated by Django 5.1.1 on 2025-02-06 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_customuser_addresse_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='addresse_mail',
            field=models.EmailField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
