version: '3'

services:
  web:
    restart: always
    build: .
    #command: "sh run.sh"
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - "MDJ_backend/.env"
    entrypoint: /app/entrypoint.sh
