# Generated by Django 5.1.1 on 2025-01-14 18:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiement', '0002_wavecheckoutsession'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-date_paiement']},
        ),
        migrations.AddField(
            model_name='payment',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payment',
            name='ref_commande',
            field=models.CharField(max_length=50),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['date_paiement'], name='paiement_pa_date_pa_d3c879_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['statut'], name='paiement_pa_statut_a9f54e_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['methode_paiement'], name='paiement_pa_methode_69a3fd_idx'),
        ),
    ]
